##### add your name and student ID
##### Name: 施盈琪
##### ID: 112524031


# Why numpy & pandas ?
### Fast, flexible, and expressive
- an efficient multi-dimensional container of generic data
### Python is increasingly being used as a scientific language. 
- Matrix and vector manipulations are extremely important for scientific computations. 
- Both NumPy and Pandas have emerged to be essential libraries for any scientific computation,


##### An Example:

In [1]:
# Creat two lists with fiev students' height and weight 
# What is BMI for the five students?
Height = [159,180,166,178,177]
Weight = [60,80,70,68,70]
type(Height)

list

In [3]:
H_meter = []
for i in Height:
    H_meter.append(i/100)
H_meter

[1.59, 1.8, 1.66, 1.78, 1.77]

In [5]:
# why we need array?
import numpy as np
Harr = np.array([159, 180, 166, 178, 177])
Warr = np.array([60, 80, 70, 68, 70])
type(Harr)

numpy.ndarray

In [8]:
Harr/100

array([1.59, 1.8 , 1.66, 1.78, 1.77])

In [9]:
Warr/(Harr/100)**2

array([23.7332384 , 24.69135802, 25.40281608, 21.46193662, 22.34351559])

### Numpy 
##### NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. NumPy is the fundamental package for scientific computing with Python

[連結](https://docs.scipy.org/doc/numpy/reference/routines.html)

In [13]:
# Array 之中的每一個元素都必須是相同型態
# NumPy is used to work with arrays with the same datatype elements.
import numpy as np
print(np.array([1, 1.12, 555, "ncu"])) #all to str
print(np.array([1, 1.12, 555])) #all to float

['1' '1.12' '555' 'ncu']
[  1.     1.12 555.  ]


In [17]:
import numpy as np 
# 使用numpy 採用np簡寫
# NumPy package can be referred to as np instead of numpy.

array1 = np.array([1,2,3])  #一維的array One Dimension Arrays
array2 = np.array([[1,2,3],[4,5,6]])  #二維的array Two Dimension Arrays

print(array2)
print('維度Number of Dimensions:',array2.ndim) 
print('行列Shape of arrays:',array2.shape) 
print('個數Number of items in arrays:',array2.size) 


[[1 2 3]
 [4 5 6]]
維度Number of Dimensions: 2
行列Shape of arrays: (2, 3)
個數Number of items in arrays: 6


In [18]:
#One Dimension Arrays
import numpy as np
a = np.array([3,6,9,12,15,18])
b = np.arange(6)  
c = np.zeros(6)  
d = np.ones(6, dtype = np.int) 
e = np.random.random(6) #random float from 0 - 1
f = b-a

print(a,b,c,d,e,f, sep="\n")
print(f<-9)
print(f==-9)


[ 3  6  9 12 15 18]
[0 1 2 3 4 5]
[0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1]
[0.09491736 0.45131427 0.91181805 0.96387691 0.44211486 0.48252374]
[ -3  -5  -7  -9 -11 -13]
[False False False False  True  True]
[False False False  True False False]


In [20]:
#Two Dimension Arrays
import numpy as np
a=np.array([[3,6,9],[12,15,18]])
b=np.arange(6).reshape((2,3))
c = np.zeros((2, 3))
d = np.ones((2,3), dtype = np.int) 
e = np.random.random((2,3)) 

print(a,b,c,d,e, sep="\n")
print(np.sum(a))
print(np.sum(a, axis=1))
print(np.sum(a, axis=0))

[[ 3  6  9]
 [12 15 18]]
[[0 1 2]
 [3 4 5]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
[[0.0570035  0.18758615 0.55351307]
 [0.39150355 0.67472512 0.76267643]]
63
[18 45]
[15 21 27]


In [21]:
# Opearation of Array加減乘除

import numpy as np
A=np.array([[2,4,6],[8,10,12]])
B=np.arange(6).reshape((2,3)) 

print(A)
print(B)

[[ 2  4  6]
 [ 8 10 12]]
[[0 1 2]
 [3 4 5]]


In [22]:
print(A+B)

[[ 2  5  8]
 [11 14 17]]


In [25]:
# array join 合併 v/hstack
import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])
         
print(np.vstack((A,B))) #vertical
print('\n',np.hstack((A,B))) #horizontal

[[1 1 1]
 [2 2 2]]

 [1 1 1 2 2 2]


In [26]:
# array split 分割
import numpy as np
a = np.arange(12).reshape((3,4))
print(a)
print(np.vsplit(a,3)) #vertical
print(np.hsplit(a,4)) #horizontal

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


##### ex: N-dimensional array

In [27]:
# creat a 2-d array with height and weight for the five studetnsnp_2d[0]
Height = [159,180,166,178,177]
Weight = [60,80,70,68,70]
np_2d = np.array([[159,180,166,178,177],
                  [60,80,70,68,70]])
np_2d

array([[159, 180, 166, 178, 177],
       [ 60,  80,  70,  68,  70]])

In [29]:
# NumPy Array Indexing
# how to select ?
# All students' height
print(np_2d[0])
# All students' weight
print(np_2d[1])
# First and Second students' weight
print(np_2d[1][:2])
# Last three students's hight and weight
print(np_2d[: , -3:])

[159 180 166 178 177]
[60 80 70 68 70]
[60 80]
[[166 178 177]
 [ 70  68  70]]


In [30]:
# Basic Statistics

# mean
print(np.mean(np_2d[0]))

# median
print(np.median(np_2d[0]))

# correlation
print(np.corrcoef(np_2d[0], np_2d[1]))

172.0
177.0
[[1.         0.76462126]
 [0.76462126 1.        ]]


In [32]:
# Searching Arrays
# You can search an array for a certain value, 
# and return the indexes that get a match.

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1) #this is index of array

print(x)
print(arr[x])

(array([0, 2, 4, 6]),)
[1 3 5 7]


In [33]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
x

(array([0, 2, 4, 6]),)

### Pandas
##### Pandas建構於Numpy上，Python做資料分析常⽤的套件
- Numpy 是array形式的，沒有欄位名稱或標籤
- Pandas 基於Numpy構建的，有列表的標籤。

- pandas is an open source, providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language. 
- Pandas' data analysis and modeling features enable users to carry out their entire data analysis workflow in Python.

##### Series

In [20]:
# Series是有index的一維array
# Creating a Series by passing a list of values, letting pandas create a default integer index.

import pandas as pd
import numpy as np

# 建立一個 Series 有整數、字串、NAN、浮點數、布林
# Creating a Series with integer, string, NAN, float, bool
s = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]])
d = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9], [10,11,12]], columns=['A','B','C'], index=['x','y','z','w'])

print(s)
print('\n',d)
print(d.info())
print(d.describe())
print(d.nunique())
print(d['A'].nunique())
print(d.shape)
print(d.size)
# 如果是numpy的array呢?
# how about array?
o = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(o)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

     A   B   C
x   1   2   3
y   4   5   6
z   7   8   9
w  10  11  12
<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, x to w
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
dtypes: int64(3)
memory usage: 128.0+ bytes
None
               A          B          C
count   4.000000   4.000000   4.000000
mean    5.500000   6.500000   7.500000
std     3.872983   3.872983   3.872983
min     1.000000   2.000000   3.000000
25%     3.250000   4.250000   5.250000
50%     5.500000   6.500000   7.500000
75%     7.750000   8.750000   9.750000
max    10.000000  11.000000  12.000000
A    4
B    4
C    4
dtype: int64
4
(4, 3)
12
[[1 2 3]
 [4 5 6]
 [7 8 9]]


##### DataFrame

In [27]:
# Create a DataFrame using a NumPy array
df = pd.DataFrame(np.random.randn(7,3))
print(df)

          0         1         2
0  0.568522 -0.730011  0.379070
1 -0.147453 -1.044220 -0.137302
2 -0.486156 -0.303613 -2.100051
3 -0.187966 -0.605882  0.974401
4 -0.498383 -0.495307  0.112905
5 -0.783428 -0.710102  0.502833
6  0.010162 -0.828406  1.256989


In [72]:
# Create a DataFrame using a NumPy array, with a datetime index
#從0-9隨機選數出21個數字並對這21個數字做運算(乘以5再+50)
eat = np.random.randint(10,size=(7,3))*5+50
dates = pd.date_range('20170812',periods=7)
df0 = pd.DataFrame(eat)
#加上欄位 with columns amd index
df1 = pd.DataFrame(eat, index=dates, columns=['Break','Lunch','Dinner'])
print(df1)

            Break  Lunch  Dinner
2017-08-12     85     95      95
2017-08-13     70     65      90
2017-08-14     50     90      65
2017-08-15     50     80      75
2017-08-16     80     60      80
2017-08-17     55     95      55
2017-08-18     95     80      80


In [73]:
# Create a DataFrame using a dictionary
df2 = pd.DataFrame({'小數float' : pd.Series(1,index=list(range(4)),dtype='float32'),
                    '整數intger' : np.array([3] * 4,dtype='int32'),
                    '時間time' : pd.Timestamp('20170812'),
                    '類別資料category' : pd.Categorical(["test","train","test","train"]),                     
                   }) 
#字典的key代表甚麼? What is the key for
# key是指columns name
# value是指表格中的內容，例如test, train, 3, 1.0, 2017-08-12..
print(df2)

   小數float  整數intger     時間time 類別資料category
0      1.0         3 2017-08-12         test
1      1.0         3 2017-08-12        train
2      1.0         3 2017-08-12         test
3      1.0         3 2017-08-12        train


In [74]:
df2

小數float  整數intger     時間time 類別資料category
0      1.0         3 2017-08-12         test
1      1.0         3 2017-08-12        train
2      1.0         3 2017-08-12         test
3      1.0         3 2017-08-12        train

In [75]:
#DataFrame的屬性
print(df2)
print(df2.dtypes)
print(df2.index) #print(df2.columns), print(df2.values)
print(df2.describe()) #有甚麼要注意的呢? 只會對數值做運算敘述

print(df2.T)
print(df2.sort_index(axis=1, ascending=False))
print(df2.sort_values(by='類別資料category'))

   小數float  整數intger     時間time 類別資料category
0      1.0         3 2017-08-12         test
1      1.0         3 2017-08-12        train
2      1.0         3 2017-08-12         test
3      1.0         3 2017-08-12        train
小數float                float32
整數intger                 int32
時間time          datetime64[ns]
類別資料category          category
dtype: object
Int64Index([0, 1, 2, 3], dtype='int64')
       小數float  整數intger
count      4.0       4.0
mean       1.0       3.0
std        0.0       0.0
min        1.0       3.0
25%        1.0       3.0
50%        1.0       3.0
75%        1.0       3.0
max        1.0       3.0
                                0                    1                    2  \
小數float                         1                    1                    1   
整數intger                        3                    3                    3   
時間time        2017-08-12 00:00:00  2017-08-12 00:00:00  2017-08-12 00:00:00   
類別資料category                 test                train  

In [76]:
df2

小數float  整數intger     時間time 類別資料category
0      1.0         3 2017-08-12         test
1      1.0         3 2017-08-12        train
2      1.0         3 2017-08-12         test
3      1.0         3 2017-08-12        train

In [77]:
print(df2.dtypes)

小數float                float32
整數intger                 int32
時間time          datetime64[ns]
類別資料category          category
dtype: object


In [78]:
print(df2.index) #print(df2.columns), print(df2.values)

Int64Index([0, 1, 2, 3], dtype='int64')


In [79]:
#只會對數值做運算敘述
print(df2.describe(include='all')) #有甚麼要注意的呢? Notice that...

        小數float  整數intger               時間time 類別資料category
count       4.0       4.0                    4            4
unique      NaN       NaN                    1            2
top         NaN       NaN  2017-08-12 00:00:00        train
freq        NaN       NaN                    4            2
first       NaN       NaN  2017-08-12 00:00:00          NaN
last        NaN       NaN  2017-08-12 00:00:00          NaN
mean        1.0       3.0                  NaN          NaN
std         0.0       0.0                  NaN          NaN
min         1.0       3.0                  NaN          NaN
25%         1.0       3.0                  NaN          NaN
50%         1.0       3.0                  NaN          NaN
75%         1.0       3.0                  NaN          NaN
max         1.0       3.0                  NaN          NaN


<ipython-input-79-c78d8ec41c2f>:2: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  print(df2.describe(include='all')) #有甚麼要注意的呢? Notice that...


In [80]:
df2.T

0                    1                    2  \
小數float                         1                    1                    1   
整數intger                        3                    3                    3   
時間time        2017-08-12 00:00:00  2017-08-12 00:00:00  2017-08-12 00:00:00   
類別資料category                 test                train                 test   

                                3  
小數float                         1  
整數intger                        3  
時間time        2017-08-12 00:00:00  
類別資料category                train

In [81]:
df2.sort_index(axis=0, ascending=False)

小數float  整數intger     時間time 類別資料category
3      1.0         3 2017-08-12        train
2      1.0         3 2017-08-12         test
1      1.0         3 2017-08-12        train
0      1.0         3 2017-08-12         test

In [82]:
df2.sort_values(by='類別資料category')

小數float  整數intger     時間time 類別資料category
0      1.0         3 2017-08-12         test
2      1.0         3 2017-08-12         test
1      1.0         3 2017-08-12        train
3      1.0         3 2017-08-12        train

##### Viewing and selecting data

In [83]:
df1

Break  Lunch  Dinner
2017-08-12     85     95      95
2017-08-13     70     65      90
2017-08-14     50     90      65
2017-08-15     50     80      75
2017-08-16     80     60      80
2017-08-17     55     95      55
2017-08-18     95     80      80

In [84]:
# View the top and bottom rows of a data frame:

In [85]:
df1.head(3)

Break  Lunch  Dinner
2017-08-12     85     95      95
2017-08-13     70     65      90
2017-08-14     50     90      65

In [86]:
df1.tail(3)

Break  Lunch  Dinner
2017-08-16     80     60      80
2017-08-17     55     95      55
2017-08-18     95     80      80

##### Complete list of Selection with examples:
- Selecting a single column
- Selection by label
- Selection by position

In [87]:
df1

Break  Lunch  Dinner
2017-08-12     85     95      95
2017-08-13     70     65      90
2017-08-14     50     90      65
2017-08-15     50     80      75
2017-08-16     80     60      80
2017-08-17     55     95      55
2017-08-18     95     80      80

In [88]:
# Selecting breakfast
df1['Break']

2017-08-12    85
2017-08-13    70
2017-08-14    50
2017-08-15    50
2017-08-16    80
2017-08-17    55
2017-08-18    95
Freq: D, Name: Break, dtype: int64

In [89]:
# Selecting the first three day
df1.head(3)

Break  Lunch  Dinner
2017-08-12     85     95      95
2017-08-13     70     65      90
2017-08-14     50     90      65

In [90]:
##### select by label
# Selecting one assiged day
print(df1.loc['2017-08-12'])

# Selecting two assiged days
print(df1.loc[['2017-08-12','2017-08-16']])

# Selecting Breakfast and Lunch in all days
print(df1.loc[:, ['Break', 'Lunch']])

print(df1[['Break', 'Lunch']])

df1.loc[['2017-08-12', '2017-08-13'], ['Break', 'Lunch']]

Break     85
Lunch     95
Dinner    95
Name: 2017-08-12 00:00:00, dtype: int64
            Break  Lunch  Dinner
2017-08-12     85     95      95
2017-08-16     80     60      80
            Break  Lunch
2017-08-12     85     95
2017-08-13     70     65
2017-08-14     50     90
2017-08-15     50     80
2017-08-16     80     60
2017-08-17     55     95
2017-08-18     95     80
            Break  Lunch
2017-08-12     85     95
2017-08-13     70     65
2017-08-14     50     90
2017-08-15     50     80
2017-08-16     80     60
2017-08-17     55     95
2017-08-18     95     80


Break  Lunch
2017-08-12     85     95
2017-08-13     70     65

In [104]:
#select by position
print(df1.iloc[3, 1])
print(df1.iloc[3:5, 1:3], '\n')
print(df1.loc[:, 'Dinner'], '\n')
print(df1.loc[:, ['Lunch', 'Dinner']])

80
            Lunch  Dinner
2017-08-15     80      75
2017-08-16     60      80 

2017-08-12    95
2017-08-13    90
2017-08-14    65
2017-08-15    75
2017-08-16    80
2017-08-17    55
2017-08-18    80
Freq: D, Name: Dinner, dtype: int64 

            Lunch  Dinner
2017-08-12     95      95
2017-08-13     65      90
2017-08-14     90      65
2017-08-15     80      75
2017-08-16     60      80
2017-08-17     95      55
2017-08-18     80      80


##### How To Filter Pandas Dataframe By Values of Column?

In [58]:
# Looking for days when the lunch bill exceeds 80
print(df1[df1['Lunch']>80])

            Break  Lunch  Dinner
2017-08-13     95     85      85


In [65]:
# Looking for days with two conditions
print(df1[(df1['Lunch'] > 70) & (df1['Dinner'] > 60)])
print(df1[(df1['Lunch'] > 80) | (df1['Break'] < 70)])

            Break  Lunch  Dinner
2017-08-12     75     80      85
2017-08-13     95     85      85
            Break  Lunch  Dinner
2017-08-13     95     85      85
2017-08-14     60     75      50
2017-08-15     50     60      60
2017-08-16     55     55      70
2017-08-17     65     65      80
2017-08-18     50     75      55


In [67]:
# What is the following statments?

df1.iloc[2,2] = 95 #更改df1中，2017-08-14的晚餐金額(50變95)
df1.loc['20170818','Lunch'] = 60 #(75變60)
df1['Dinner'][df1.Break>80] = 40 #篩選出Break中>80的行，然後將對應的Dinner設置為40
df1.loc['20170814','Break'] = np.nan #改成nan值

print(df1)

            Break  Lunch  Dinner
2017-08-12   75.0     80      85
2017-08-13   95.0     85      40
2017-08-14    NaN     75      95
2017-08-15   50.0     60      60
2017-08-16   55.0     55      70
2017-08-17   65.0     65      80
2017-08-18   50.0     60      55


In [69]:
# what is where
df1.where(df1>70)

Break  Lunch  Dinner
2017-08-12   75.0   80.0    85.0
2017-08-13   95.0   85.0     NaN
2017-08-14    NaN   75.0    95.0
2017-08-15    NaN    NaN     NaN
2017-08-16    NaN    NaN     NaN
2017-08-17    NaN    NaN    80.0
2017-08-18    NaN    NaN     NaN